# Block Child Porn as required by Hetzner BKA policy

{ +redirect{http://www.onion/} }
vs5hb2ybldb4gfja.onion
w7b5kmjonf4h6fea.onion
cm6pxkmeyhf7kryb.onion
7o6dcmajcps4tbjb.onion
75aiiotc26qp4j2y.onion
c7jh7jzl3taek4eh.onion
iecwyzlr6ydaoc4z.onion
5cez64xymwnci47y.onion
ylze62ejorjyfe7z.onion
mldiefslh2tfrpu5.onion
waivt2ksvjukhsps.onion
jkpos24pl2r3urlw.onion
opva2pilsncvtwmh.onion
46dspvfldjiqzsre.onion
c7jh7jzl3teak4eh.onion
32zaudfm5y6w3ypy.onion
kdq2y44aaas2aiu4.onion
4eiruntyxxbgfv7o.onion
xqz3u5drneuzhaeo.onion
6x77gb7ngu6nymwl.onion
kpvz7ki2v5agwt35.onion
ci3hn2uzjw2wby3z.onion
mf7ww4oo2ztz3xuv.onion
nropmqpuz7ubtfea.onion
j4ddjgxetfx2ybcx.onion
arch4jgjcyt55gb2.onion
